# Generated by Django 3.1.1 on 2020-09-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plano_de_teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoDoPlanoDeTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plano_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.planodeteste')),
            ],
        ),
    ]
