# Generated by Django 3.1.1 on 2020-12-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa_de_teste', '0004_auto_20201216_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacaointeresse',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitado'), (2, 'Aprovado')], default=1),
        ),
    ]
