# Generated by Django 3.1.1 on 2021-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='estornado',
            field=models.BooleanField(default=False),
        ),
    ]
