# Generated by Django 3.1.1 on 2021-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_lancamento_estornado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaosaque',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
