# Generated by Django 3.1.1 on 2020-09-15 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('url_acesso', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('detalhes_autenticacao', models.TextField()),
                ('versao_produto', models.CharField(max_length=50)),
                ('estado_lancamento_produto', models.CharField(max_length=100)),
                ('operadora', models.ManyToManyField(blank=True, to='plano_de_teste.Operadora')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.tipoproduto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Navegador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('versao', models.CharField(max_length=50)),
                ('plano_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.planodeteste')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('plano_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.planodeteste')),
                ('sistema_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.sistemaoperacional')),
            ],
        ),
    ]
