# Generated by Django 3.1.1 on 2020-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_teste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeteste',
            name='operadora',
            field=models.ManyToManyField(blank=True, null=True, to='plano_de_teste.Operadora'),
        ),
    ]
