# Generated by Django 3.1.1 on 2020-10-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_teste', '0002_auto_20200915_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeteste',
            name='operadora',
            field=models.ManyToManyField(blank=True, to='plano_de_teste.Operadora'),
        ),
    ]
