# Generated by Django 3.1.1 on 2020-10-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_teste', '0003_auto_20201006_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planodeteste',
            name='operadora',
        ),
        migrations.AddField(
            model_name='operadora',
            name='plano_de_teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.planodeteste'),
            preserve_default=False,
        ),
    ]
