# Generated by Django 3.1.1 on 2021-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
