# Generated by Django 3.1.1 on 2021-01-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_avaliacao_user_avaliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='user_avaliado',
        ),
    ]
