# Generated by Django 3.1.1 on 2020-09-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cenario_de_teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('resultado', models.TextField(blank=True, null=True)),
                ('data_execucao', models.DateField()),
                ('cenario_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenario_de_teste.cenariodeteste')),
            ],
        ),
        migrations.CreateModel(
            name='PreCondicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caso_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso_de_teste.casodeteste')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField()),
                ('resultado_esperado', models.TextField(blank=True, null=True)),
                ('caso_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso_de_teste.casodeteste')),
            ],
        ),
    ]
