# Generated by Django 3.1.1 on 2020-12-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caso_de_teste', '0002_auto_20201123_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casodeteste',
            name='data_execucao',
        ),
        migrations.RemoveField(
            model_name='casodeteste',
            name='resultado',
        ),
    ]
