# Generated by Django 3.1.1 on 2020-09-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caso_de_teste', '0001_initial'),
        ('plano_de_teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeFalha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_da_falha', models.TextField()),
                ('caso_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso_de_teste.casodeteste')),
                ('navegador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.navegador')),
                ('sistema_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.sistemaoperacional')),
            ],
        ),
        migrations.CreateModel(
            name='PassoReproducaoFalha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_passo', models.TextField()),
                ('registro_de_falha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_falha.registrodefalha')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoRegistroFalha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_falha', models.ImageField(upload_to='screen_anexo_registro_falha')),
                ('registro_de_falha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_falha.registrodefalha')),
            ],
        ),
    ]
