# Generated by Django 3.1.1 on 2020-12-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caso_de_teste', '0003_auto_20201203_2305'),
        ('plano_de_teste', '0004_auto_20201025_1852'),
        ('registro_de_falha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Aprovado'), (2, 'Com Falha')])),
                ('descricao_da_falha', models.TextField(blank=True, null=True)),
                ('caso_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso_de_teste.casodeteste')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.dispositivo')),
                ('navegador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.navegador')),
                ('operadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.operadora')),
                ('sistema_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plano_de_teste.sistemaoperacional')),
            ],
        ),
        migrations.RemoveField(
            model_name='anexoregistrofalha',
            name='registro_de_falha',
        ),
        migrations.RemoveField(
            model_name='passoreproducaofalha',
            name='registro_de_falha',
        ),
        migrations.DeleteModel(
            name='RegistroDeFalha',
        ),
        migrations.AddField(
            model_name='anexoregistrofalha',
            name='registro_de_teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_de_falha.registrodeteste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passoreproducaofalha',
            name='registro_de_teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_de_falha.registrodeteste'),
            preserve_default=False,
        ),
    ]
