# Generated by Django 3.1.1 on 2020-12-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caso_de_teste', '0003_auto_20201203_2305'),
        ('registro_de_falha', '0002_auto_20201221_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeteste',
            name='caso_de_teste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caso_de_teste.casodeteste'),
        ),
    ]
