# Generated by Django 3.1.1 on 2020-12-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_falha', '0003_auto_20201228_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodeteste',
            name='sistema_operacional',
        ),
    ]
